### ISSUE TITLE
How to achieve  the bounce interpolator?

### ISSUE THREAD

**Issue by ernestkamara** [sourabhgupta811/DotProgressBar#1]
Hey @sourabhgupta811, 
Thanks for this example. You save me some time. However, how can I get the views to bounce as you mentioned in your post?

Bests regards,
Ernest

**Comment by sourabhgupta811** [comment]
Hi @ernestkamara 
You can just change the getScaleAnimator UpdateListener in DotProgressBar.kt to get the bounce animation. 
For eg, You can replace the update listener animation with this code for bounce
view.translationY = it.animatedValue as Float*20

**Comment by ernestkamara** [comment]
Ok, thanks. I will give it a try.

**Comment by ernestkamara** [comment]
Thanks, It works. However, how easy to do both scaling and bouncing?

**Comment by sourabhgupta811** [comment]
You cam change several object properties in the value animator to create new loader animations.

**Comment by sourabhgupta811** [comment]
I am closing this issue now as resolved.
